version: '3.5'

services:
  squid-proxy:
    image: squid-proxy
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3128:3128"
    volumes:
      - squid_data:/var/log/squid
    networks:
      - lab

volumes:
  squid_data:
    driver: local

networks:
  lab:
    external: true